name: Backend

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: ./server
      - name: Build
        run: npm run build
        working-directory: ./server
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        - name: Copy files to the server
        # заливаем файлы при помощи rsync
        run: |
          rsync -a --progress --human-readable --delete \
          # исключить все, что есть в .gitignore
          --exclude-from '.gitignore' \
          # не загружаем .gitignore
          --exclude .gitignore \
          # не загружаем .git
          --exclude .git \
          # Не удаляем директорию с нашим фронтендом
          --exclude public \
          . deploy@ec2-16-170-230-203.eu-north-1.compute.amazonaws.com:~/blog-crafter/server
        working-directory: ./server
      - name: Restart the application
        run: |
          ssh deploy@ec2-16-170-230-203.eu-north-1.compute.amazonaws.com "pushd ~/blog-crafter/server && npm install && popd && pm2 restart ecosystem.config.js"
