name: Backend

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: ./server
      - name: Build
        run: npm run build
        working-directory: ./server
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Copy files to the server
        run: |
          rsync -a --progress --human-readable --delete \
          --exclude node_modules \
          --exclude ecosystem.config.js \
          --exclude .git \
          . deploy@ec2-13-51-210-134.eu-north-1.compute.amazonaws.com:~/blog-crafter/server
        working-directory: ./server
      - name: Restart the application
        run: |
          ssh deploy@ec2-13-51-210-134.eu-north-1.compute.amazonaws.com "cd ~/blog-crafter/server && npm install && cd ~/blog-crafter && pm2 restart ecosystem.config.js"
