name: Build and Deploy

on:
  push:
    branches: [main]

  # специальное событие, которое происходит при ручном вызове workflow
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci --ignore-scripts
        working-directory: ./client
      # Запуск сборки
      - name: Build
        run: npm run build
        working-directory: ./client
        env:
          API_URL: ${{ secrets.API_URL }}
      # Дальше по аналогии с backend, просто загружаем на сервер
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          # ставим нужные безопасные права
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Copy files to the server
        run: |
          scp -r dist/* deploy@ec2-16-170-230-203.eu-north-1.compute.amazonaws.com:~/blog-crafter/client
        working-directory: ./client
